const tracks = [
  { id: 1,  title: "SIDO - BILDER IM KOPF", views: "98M", yearsAgo: "13", videoId: "RveIJFR7LV4" },
  { id: 2,  title: "SIDO - SCHLECHTES VORBILD", views: "80M", yearsAgo: "18", videoId: "9jjvlT78pU4" },
  { id: 3,  title: "ALLIGATOAH - WILLST DU", views: "74M", yearsAgo: "12", videoId: "opoDBF_b-fg" },
  { id: 4,  title: "TRAILERPARK - FLEDERMAUSLAND", views: "26M", yearsAgo: "13", videoId: "EAC-2ttHCyk" },
  { id: 5,  title: "SIDO & B-TIGHT - HOL DOCH DIE POLIZEI / BIS ZUR SONNE", views: "24M", yearsAgo: "14", videoId: "lqiJCUhuDYg" },
  { id: 6,  title: "EKO FRESH - KÖLN KALK EHRENMORD", views: "23M", yearsAgo: "14", videoId: "YMsOf-onIow" },
  { id: 7,  title: "SIDO - AUGEN AUF", views: "22M", yearsAgo: "11", videoId: "i5-NnEGU29I" },
  { id: 8,  title: "SIDO - MEIN BLOCK", views: "19M", yearsAgo: "15", videoId: "H4odG4d_88g" },
  { id: 9,  title: "NATE57 - BLAULICHT", views: "17M", yearsAgo: "16", videoId: "1dIDNyFdRkk" },
  { id: 10, title: "SIDO - WEIHNACHTSSONG", views: "16M", yearsAgo: "15", videoId: "i-unBLOI7uM" },
  { id: 11, title: "SIDO - SPRING RAUF", views: "16M", yearsAgo: "13", videoId: "P1jIkON8HFo" },
  { id: 12, title: "SIDO - MEIN TESTAMENT", views: "14M", yearsAgo: "12", videoId: "ota8CqBUQmc" },
  { id: 13, title: "HAFTBEFEHL - HALT DIE FRESSE 03 NR. 78", views: "14M", yearsAgo: "15", videoId: "dTbjV92hHFQ" },
  { id: 14, title: "TONI DER ASSI - HALT DIE FRESSE 04 NR. 186", views: "13M", yearsAgo: "14", videoId: "B3lU9TdY2sU" },
  { id: 15, title: "SIDO - STRIP FÜR MICH (FEAT. KITTY KAT)", views: "13M", yearsAgo: "15", videoId: "IjEgwfi4y_E" },
  { id: 16, title: "OLEXESH - HALT DIE FRESSE 05 NR. 251", views: "13M", yearsAgo: "13", videoId: "GutEQy7Vc6E" },
  { id: 17, title: "SIDO - EIN TEIL VON MIR", views: "13M", yearsAgo: "19", videoId: "aTfDfqOTX6M" },
  { id: 18, title: "EKO FRESH - HALT DIE FRESSE 04 NR. 157", views: "13M", yearsAgo: "14", videoId: "eIIDS6D1NOI" },
  { id: 19, title: "SIDO - HERZ", views: "13M", yearsAgo: "17", videoId: "-ikcvxhaDBg" },
  { id: 20, title: "KC REBELL - AMK (AMINA KOYIM)", views: "12M", yearsAgo: "13", videoId: "TTN9MR97JyQ" },
  { id: 21, title: "MASSIV FEAT. FARID BANG & KOLLEGAH - MASSAKA KOKAIN 2", views: "11M", yearsAgo: "14", videoId: "b59tJJ-a46c" },
  { id: 22, title: "FARID BANG - HALT DIE FRESSE 03 NR. 99", views: "11M", yearsAgo: "15", videoId: "jGXMv9RVJbI" },
  { id: 23, title: "EKO FRESH FEAT. NINO DE ANGELO - JENSEITS VON EDEN", views: "10M", yearsAgo: "14", videoId: "hN023L75GgM" },
  { id: 24, title: "FLER - NDW 2005 / NEUE DEUTSCHE WELLE", views: "10M", yearsAgo: "15", videoId: "RkoRz656OOM" },
  { id: 25, title: "ALLSTARS - HALT DIE FRESSE 03 NR. 73", views: "10M", yearsAgo: "15", videoId: "3YpfrlazPvQ" },
  { id: 26, title: "CAPITAL BRA - HALT DIE FRESSE NR. 355", views: "9.8M", yearsAgo: "10", videoId: "xke_rtMfADc" },
  { id: 27, title: "SIDO, KITTY KAT, FLER, TONY D, B-TIGHT - ANSAGE 8 / 5 KRASSE RAPPER", views: "9.6M", yearsAgo: "17", videoId: "9w5W97Cm_eo" },
  { id: 28, title: "KC REBELL FEAT. MOE PHOENIX - SIEH ES ENDLICH EIN", views: "9.4M", yearsAgo: "14", videoId: "bzwTHXIZsdw" },
  { id: 29, title: "NATE57 - WAFFENFREIE ZONE", views: "9.2M", yearsAgo: "15", videoId: "kufK98jYBDk" },
  { id: 30, title: "NATE57 & TELLY TELLZ - HALT DIE FRESSE 02 NR. 49", views: "8.8M", yearsAgo: "15", videoId: "nxsouyFUYbo" },
  { id: 31, title: "SIDO & HARRIS - DEINE LIEBLINGSRAPPER - STEH WIEDER AUF", views: "8.8M", yearsAgo: "15", videoId: "J63bFasPUqk" },
  { id: 32, title: "NATE57 - FICK DIE WELT", views: "8.6M", yearsAgo: "14", videoId: "ZAvs-92vAiI" },
  { id: 33, title: "ALPA GUN FEAT. SIDO - HALT DIE FRESSE 01 NR. 04", views: "8.4M", yearsAgo: "16", videoId: "9PU_ZqtfVeY" },
  { id: 34, title: "SIDO - HALT DEIN MAUL", views: "7.9M", yearsAgo: "11", videoId: "L5c9XSyWeUY" },
  { id: 35, title: "CELO & ABDI - HALT DIE FRESSE 04 NR. 207", views: "7.8M", yearsAgo: "13", videoId: "y5eN6UIFMt8" },
  { id: 36, title: "HAFTBEFEHL - HALT DIE FRESSE 01 NR. 32", views: "7.6M", yearsAgo: "16", videoId: "dDnhthI27Fg" },
  { id: 37, title: "SXTN - WIR SIND FRIEDLICH - HALT DIE FRESSE NR. 364", views: "7.6M", yearsAgo: "9", videoId: "xVP1R1dRnW4" },
  { id: 38, title: "KING KLICKS / SIDO FEAT. B.S.H. - MEINE JORDANS", views: "7.6M", yearsAgo: "13", videoId: "MVfk28LvtwA" },
  { id: 39, title: "AK AUSSERKONTROLLE FEAT. UNDACAVA - ECHTE BERLINER", views: "7.5M", yearsAgo: "10", videoId: "6JIuNJxiznU" },
  { id: 40, title: "XATAR / CELO & ABDI / CAPO / HAFTBEFEHL - HALT DIE FRESSE 04 NR. 215", views: "7.3M", yearsAgo: "13", videoId: "at_m5H04qmQ" },
  { id: 41, title: "1UP - WHOLECAR - ROPE ESCAPE - BERLIN", views: "7.3M", yearsAgo: "8", videoId: "Y9Lm0dkkVAw" },
  { id: 42, title: "TRAILERPARK - SEXUALETHISCH DESORIENTIERT", views: "7.1M", yearsAgo: "11", videoId: "AR2gGQo2cmQ" },
  { id: 43, title: "AK AUSSERKONTROLLE - FLEXSCHEIBE", views: "7M", yearsAgo: "10", videoId: "KW_k3jkNUzg" },
  { id: 44, title: "AK AUSSERKONTROLLE - PANZAKNACKA", views: "6.8M", yearsAgo: "9", videoId: "hR6hx9k_MhY" },
  { id: 45, title: "ALLSTARS - HALT DIE FRESSE 04 NR. 155", views: "6.7M", yearsAgo: "14", videoId: "KDaT2wRH5bU" },
  { id: 46, title: "HAFTBEFEHL - HALT DIE FRESSE 04 NR. 187", views: "6.6M", yearsAgo: "13", videoId: "vmX6OuVjWpA" },
  { id: 47, title: "AK AUSSERKONTROLLE - 2065", views: "6.5M", yearsAgo: "9", videoId: "YTwodFfFwfo" },
  { id: 48, title: "ALLIGATOAH - FICK IHN DOCH", views: "6.3M", yearsAgo: "12", videoId: "2p_7338B5ow" },
  { id: 49, title: "KURDO FEAT. ATILLAH 78 - 11TA STOCK SOUND", views: "6.1M", yearsAgo: "14", videoId: "J3Zr8gMuvkQ" },
  { id: 50, title: "SIDO - MAMA IST STOLZ", views: "6M", yearsAgo: "15", videoId: "4LaDeQS3F-8" },
  { id: 51, title: "ALLIGATOAH - WILLST DU (LYRICS VERSION)", views: "5.9M", yearsAgo: "12", videoId: "Pyi7T8gTb2w" },
  { id: 52, title: "ALLIGATOAH - HALT DIE FRESSE 05 NR. 297", views: "5.7M", yearsAgo: "12", videoId: "bmkxmnnst_k" },
  { id: 53, title: "SIDO - DU BIST SCHEISSE", views: "5.7M", yearsAgo: "12", videoId: "B-4D98OFtw8" },
  { id: 54, title: "AZAD - HALT DIE FRESSE 01 NR. 20", views: "5.6M", yearsAgo: "16", videoId: "CZykq4-qtwI" },
  { id: 55, title: "SIDO / FLER / B-TIGHT - AGGRO TEIL 4 - ANSAGE 4", views: "5.5M", yearsAgo: "15", videoId: "4a-I3cRovfg" },
  { id: 56, title: "MANUELLSEN FEAT. HAFTBEFEHL - GENERATION KANAK", views: "5.4M", yearsAgo: "15", videoId: "aZPoH6Kz-NY" },
  { id: 57, title: "ALPA GUN - HALT DIE FRESSE GOLD NR. 01", views: "5.4M", yearsAgo: "14", videoId: "qqmocYS-2AI" },
  { id: 58, title: "AK AUSSERKONTROLLE FEAT. UNDACAVA - 2 MINUTEN", views: "5.3M", yearsAgo: "10", videoId: "lHjdh72uLxw" },
  { id: 59, title: "SIDO - ARSCHFICKSONG", views: "5.1M", yearsAgo: "12", videoId: "tzvuGdvvvkU" },
  { id: 60, title: "SIDO - HALT DIE FRESSE 05 NR. 260", views: "5.1M", yearsAgo: "13", videoId: "tph0Pqb4bUs" }
];
